//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Test.java
//
//  Created by dst3708 on 4/1/13.
//

//note:
//in modified morgan's code
//gridSize = total grids
//difficulty = maxi number which the math operation runs below
//operation = 'addition' 'subtraction' and 'combination'

#import "stdlib.h"
#import "MathGame.h"

@implementation MathGame

@synthesize count;
NSMutableArray *cardArray;
int answers[20];
BOOL duplicate = false;

int count = 0;

+ (NSMutableArray*)generateGrid:(int)gridSize
                 withDifficulty:(int)difficulty
                         withOp:(unichar)operation {
    NSLog(@"GENERATING MATH GRID");
    count = 0;
    
    
    cardArray = [NSMutableArray array];
    NSLog(@"about to get numbers for math problems");

    
    if (operation == 'a') {
        while(count < gridSize/2) {
            NSLog(@"a is the problem");

            [self getNumbers:difficulty add:YES];
        }
    }
    else if (operation == 's') {
        while(count < gridSize/2) {
            NSLog(@"s this the problem");

            [self getNumbers:difficulty add:NO];
        }
    }
    else if (operation == 'b') {
        NSLog(@"b this the problem");

        while(count < gridSize/4) {
            [self getNumbers:difficulty add:NO];
            
            NSLog(@"b this the problem2");
            
        }
        while(count < gridSize/2) {
            [self getNumbers:difficulty add:YES];
            NSLog(@"b this the problem3");
        }
    }
    else {
        NSLog(@"is this the problem");
    }
    NSLog(@"is this the problem2");

    return cardArray;
}

+ (void)getNumbers:(int)limit
               add:(BOOL)op {
    
    duplicate = false;
    int a, b, c, d;
    if (limit == 10) {
        c = arc4random() % 11;
        b = arc4random() % (c+1);
        a = c - b;
    }
    else {
        limit = limit / 2;
        a = arc4random() % limit + 1;
        b = arc4random() % limit + 1;
        c = a + b;
    }
    if (op) {
        d = c;
        }
    else {
        d = a;
    }
    for (int x = 0; x < count; x++) {
        if (answers[x] == d){
            duplicate = true;
        }
    }
    if (!duplicate){
        answers[count] = d;
        [self getCards:op withA:a withB:b withC:c];
        count++;
    }
}

+ (void)getCards:(BOOL)op
           withA:(int)a
           withB:(int)b
           withC:(int)c {
    NSString *card1;
    NSString *card2;
    if (op) {
        card1 = [NSString stringWithFormat:@"%d + %d", a, b];
        card2 = [NSString stringWithFormat:@"%d", c];
    }
    else {
        card1 = [NSString stringWithFormat:@"%d - %d", c, b];
        card2 = [NSString stringWithFormat:@"%d", a];
    }
    NSLog(@"adding math cards to card array");
    [cardArray addObject: card1];
    [cardArray addObject: card2];
}

@end
