//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Test.java
//
//  Created by dst3708 on 4/1/13.
//

@class IOSObjectArray;


@interface MathGame : NSObject {
    int count;
}

@property int count;

+ (NSMutableArray*)generateGrid:(int)gridSize
                 withDifficulty:(int)difficulty
                         withOp:(unichar)operation;
+ (void)getNumbers:(int)limit
               add:(BOOL)op;
+ (void)getCards:(BOOL)op
           withA:(int)a
           withB:(int)b
           withC:(int)c;
@end
